version: "3"

services:
  simple_http_chatapp:
    depends_on:
      - table-creator
    image: simple_http_chatapp
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      DYNAMODB_ENDPOINT_URL: http://dynamodb-local:8000
      DYNAMODB_TABLE_NAME: ${DYNAMODB_TABLE_NAME}
      DB_TYPE: ${DB_TYPE}
      HTTP_PORT: ${HTTP_PORT}
      AWS_XRAY_DAEMON_ADDRESS: xray-daemon:2000
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOST: mongodb
      MONGODB_PORT: "27017"
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"

  # mongodb:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  #   ports:
  #     - "27017:27017"

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  table-creator:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    container_name: table-creator
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      DYNAMODB_TABLE_NAME: ${DYNAMODB_TABLE_NAME}
    command:
      dynamodb create-table --table-name ${DYNAMODB_TABLE_NAME} --attribute-definitions AttributeName=connectionId,AttributeType=S --key-schema AttributeName=connectionId,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://dynamodb-local:8000 --region ${AWS_DEFAULT_REGION}

  # X-Ray Daemon that actually authenticates via locally-stored AWS credentials
  xray-daemon:
    command: "xray-daemon -o"
    image: "amazon/aws-xray-daemon"
    container_name: xray-daemon
    environment:
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: ${REAL_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${REAL_AWS_SECRET_ACCESS_KEY}
